import maplibregl from "maplibre-gl";
import { layers, namedFlavor } from "@protomaps/basemaps";
import { Protocol } from "pmtiles";
import { LOCAL_GLYPHS_PATH, LOCAL_SPRITE_PATH } from "../data/offlineBengaluru.js";
import { emptyFeatureCollection } from "./navigation.js";

const MAP_ICON_IDS = {
  waterReservoir: "water-reservoir-icon",
  powerSubstation: "power-substation-icon",
  hospital: "hospital-icon",
  fireStation: "fire-station-icon",
  policeStation: "police-station-icon",
};

const MAP_ICON_PATHS = {
  waterReservoir: "/icons/water-reservoir.png",
  powerSubstation: "/icons/power-substation.png",
  hospital: "/icons/hospital-plus.png",
  fireStation: "/icons/fire-truck.png",
  policeStation: "/icons/police-badge.png",
};

export function getPmtilesProtocol() {
  if (!globalThis.__bengaluruPmtilesProtocol) {
    const protocol = new Protocol({ metadata: true });
    maplibregl.addProtocol("pmtiles", protocol.tile);
    globalThis.__bengaluruPmtilesProtocol = protocol;
  }

  return globalThis.__bengaluruPmtilesProtocol;
}

export function getMapPadding() {
  if (window.innerWidth < 720) {
    return { top: 28, right: 16, bottom: 16, left: 16 };
  }

  return { top: 18, right: 18, bottom: 18, left: 18 };
}

export function createEmptyOverlayData() {
  return {
    boundary: emptyFeatureCollection(),
    civic: emptyFeatureCollection(),
    trafficSignals: emptyFeatureCollection(),
    trafficSignalDirections: emptyFeatureCollection(),
    waterGrid: emptyFeatureCollection(),
    waterValves: emptyFeatureCollection(),
    powerGrid: emptyFeatureCollection(),
    powerSubstations: emptyFeatureCollection(),
    powerTransformers: emptyFeatureCollection(),
    hotspots: emptyFeatureCollection(),
    hotspotCenters: emptyFeatureCollection(),
  };
}

export function createStyle(pmtilesUrl) {
  const origin = window.location.origin;
  const flavor = namedFlavor("light");
  const baseLayers = layers("basemap", flavor);
  const labelLayers = layers("basemap", flavor, { lang: "en", labelsOnly: true });

  return {
    version: 8,
    glyphs: `${origin}${LOCAL_GLYPHS_PATH}`,
    sprite: `${origin}${LOCAL_SPRITE_PATH}`,
    sources: {
      basemap: {
        type: "vector",
        url: `pmtiles://${pmtilesUrl}`,
        attribution:
          "&copy; <a href='https://www.openstreetmap.org/copyright'>OpenStreetMap</a> &copy; <a href='https://protomaps.com'>Protomaps</a>",
      },
      boundary: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      campuses: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      campusEmergencyAlert: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      campusEmergencyRoutes: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      campusEmergencyRouteTargets: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      campusBuildings: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      civic: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      synthverseScanArea: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      synthverseEmergencyFacilities: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      trafficEvents: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      trafficEventZones: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      trafficSignals: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      trafficSignalDirections: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      trafficSignalActiveDirections: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      trafficSignalActivePoints: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      trafficHeatmap: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      waterZones: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      waterPressureHeatmap: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      waterIncidentHeatmap: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      waterNodes: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      waterGridVisible: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      waterValves: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      waterBreaks: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      powerZones: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      powerNodes: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      powerGridVisible: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      powerSubstations: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      powerTransformers: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      powerIncidents: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      hotspots: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      hotspotCenters: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      vehicleProbeArea: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      vehicleProbeCenter: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      route: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      routeEndpoints: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
      vehicles: {
        type: "geojson",
        data: emptyFeatureCollection(),
      },
    },
    layers: [
      ...baseLayers,
      {
        id: "bengaluru-boundary-fill",
        type: "fill",
        source: "boundary",
        paint: {
          "fill-color": "#2563eb",
          "fill-opacity": 0.04,
        },
      },
      {
        id: "campus-fill",
        type: "fill",
        source: "campuses",
        minzoom: 0,
        paint: {
          "fill-color": "#67e8f9",
          "fill-opacity": 0.18,
        },
      },
      {
        id: "campus-emergency-fill",
        type: "fill",
        source: "campusEmergencyAlert",
        paint: {
          "fill-color": "#dc2626",
          "fill-opacity": 0.16,
        },
      },
      {
        id: "campus-emergency-outline",
        type: "line",
        source: "campusEmergencyAlert",
        layout: {
          "line-join": "round",
          "line-cap": "round",
        },
        paint: {
          "line-color": "#dc2626",
          "line-width": [
            "interpolate",
            ["linear"],
            ["zoom"],
            10,
            1.8,
            16,
            3.8,
          ],
          "line-opacity": 0.96,
        },
      },
      {
        id: "campus-emergency-routes",
        type: "line",
        source: "campusEmergencyRoutes",
        layout: {
          "line-join": "round",
          "line-cap": "round",
        },
        paint: {
          "line-color": "#dc2626",
          "line-width": [
            "interpolate",
            ["linear"],
            ["zoom"],
            10,
            2.2,
            16,
            4.4,
          ],
          "line-opacity": 0.94,
        },
      },
      {
        id: "campus-emergency-target-points",
        type: "circle",
        source: "campusEmergencyRouteTargets",
        paint: {
          "circle-radius": [
            "interpolate",
            ["linear"],
            ["zoom"],
            10,
            5.2,
            16,
            8.6,
          ],
          "circle-color": "#dc2626",
          "circle-stroke-color": "#ffffff",
          "circle-stroke-width": 1.8,
          "circle-opacity": 0.98,
        },
      },
      {
        id: "campus-emergency-target-labels",
        type: "symbol",
        source: "campusEmergencyRouteTargets",
        minzoom: 10,
        layout: {
          "text-field": ["get", "label"],
          "text-size": [
            "interpolate",
            ["linear"],
            ["zoom"],
            10,
            10,
            16,
            13,
          ],
          "text-offset": [0, 1.15],
          "text-anchor": "top",
        },
        paint: {
          "text-color": "#7f1d1d",
          "text-halo-color": "#ffffff",
          "text-halo-width": 1.3,
        },
      },
      {
        id: "buildings-3d",
        type: "fill-extrusion",
        source: "basemap",
        "source-layer": "buildings",
        minzoom: 12,
        filter: ["in", "kind", "building", "building_part"],
        paint: {
          "fill-extrusion-color": "#c6ccd3",
          "fill-extrusion-opacity": 0.85,
          "fill-extrusion-height": [
            "interpolate",
            ["linear"],
            ["zoom"],
            12,
            0,
            13.5,
            [
              "case",
              ["has", "height"],
              ["to-number", ["get", "height"], 16],
              ["case", ["has", "render_height"], ["to-number", ["get", "render_height"], 16], 16],
            ],
          ],
          "fill-extrusion-base": [
            "case",
            ["has", "min_height"],
            ["to-number", ["get", "min_height"], 0],
            ["case", ["has", "render_min_height"], ["to-number", ["get", "render_min_height"], 0], 0],
          ],
        },
      },
      {
        id: "bengaluru-boundary-line",
        type: "line",
        source: "boundary",
        layout: {
          "line-join": "round",
          "line-cap": "round",
        },
        paint: {
          "line-color": "#0f172a",
          "line-width": [
            "interpolate",
            ["linear"],
            ["zoom"],
            9,
            1.5,
            12,
            2.4,
            15,
            4.5,
          ],
          "line-opacity": 0.92,
        },
      },
      {
        id: "campus-buildings-3d",
        type: "fill-extrusion",
        source: "campusBuildings",
        minzoom: 11.5,
        paint: {
          "fill-extrusion-color": "#0891b2",
          "fill-extrusion-height": [
            "+",
            ["coalesce", ["to-number", ["get", "heightMeters"]], 18],
            1,
          ],
          "fill-extrusion-base": 0,
          "fill-extrusion-opacity": 0.92,
        },
      },
      {
        id: "water-pressure-heatmap",
        type: "heatmap",
        source: "waterPressureHeatmap",
        maxzoom: 16,
        paint: {
          "heatmap-weight": ["coalesce", ["to-number", ["get", "weight"]], 0],
          "heatmap-intensity": [
            "interpolate",
            ["linear"],
            ["zoom"],
            8,
            1.2,
            11,
            1.45,
            13,
            1.72,
            16,
            1.92,
          ],
          "heatmap-color": [
            "interpolate",
            ["linear"],
            ["heatmap-density"],
            0,
            "rgba(219,234,254,0)",
            0.06,
            "rgba(219,234,254,0.42)",
            0.18,
            "rgba(191,219,254,0.62)",
            0.34,
            "rgba(96,165,250,0.76)",
            0.58,
            "rgba(59,130,246,0.86)",
            0.8,
            "rgba(37,99,235,0.94)",
            1,
            "rgba(23,37,84,0.98)",
          ],
          "heatmap-radius": [
            "interpolate",
            ["linear"],
            ["zoom"],
            8,
            34,
            11,
            46,
            13,
            58,
            16,
            74,
          ],
          "heatmap-opacity": [
            "interpolate",
            ["linear"],
            ["zoom"],
            8,
            0.92,
            11,
            0.88,
            14,
            0.8,
            16,
            0.66,
          ],
        },
      },
      {
        id: "water-incident-heatmap",
        type: "heatmap",
        source: "waterIncidentHeatmap",
        maxzoom: 16,
        paint: {
          "heatmap-weight": ["coalesce", ["to-number", ["get", "weight"]], 0],
          "heatmap-intensity": [
            "interpolate",
            ["linear"],
            ["zoom"],
            8,
            0.98,
            12,
            1.22,
            13,
            1.34,
            16,
            1.48,
          ],
          "heatmap-color": [
            "interpolate",
            ["linear"],
            ["heatmap-density"],
            0,
            "rgba(249,115,22,0)",
            0.08,
            "rgba(254,240,138,0.32)",
            0.24,
            "rgba(251,146,60,0.54)",
            0.48,
            "rgba(249,115,22,0.72)",
            0.78,
            "rgba(220,38,38,0.88)",
            1,
            "rgba(127,29,29,0.98)",
          ],
          "heatmap-radius": [
            "interpolate",
            ["linear"],
            ["zoom"],
            8,
            26,
            11,
            36,
            13,
            44,
            16,
            58,
          ],
          "heatmap-opacity": [
            "interpolate",
            ["linear"],
            ["zoom"],
            8,
            0.84,
            11,
            0.78,
            14,
            0.68,
            16,
            0.54,
          ],
        },
      },
      {
        id: "campus-labels",
        type: "symbol",
        source: "campuses",
        minzoom: 0,
        layout: {
          "text-field": ["get", "label"],
          "text-size": [
            "interpolate",
            ["linear"],
            ["zoom"],
            11.2,
            11,
            16,
            14,
          ],
          "text-font": ["Noto Sans Regular"],
          "text-offset": [0, -0.2],
          "text-allow-overlap": true,
        },
        paint: {
          "text-color": "#0f172a",
          "text-halo-color": "#ffffff",
          "text-halo-width": 1.3,
        },
      },
      {
        id: "traffic-direction-cones",
        type: "fill-extrusion",
        source: "trafficSignalDirections",
        minzoom: 10,
        paint: {
          "fill-extrusion-color": "#7dd3fc",
          "fill-extrusion-height": [
            "interpolate",
            ["linear"],
            ["zoom"],
            10,
            3,
            14,
            8,
          ],
          "fill-extrusion-base": 0,
          "fill-extrusion-opacity": 0.34,
        },
      },
      {
        id: "traffic-direction-arrows",
        type: "symbol",
        source: "trafficSignalDirections",
        minzoom: 10,
        layout: {
          "text-field": "▲",
          "text-font": ["Noto Sans Regular"],
          "text-size": [
            "interpolate",
            ["linear"],
            ["zoom"],
            10,
            9,
            13,
            12,
            16,
            16,
          ],
          "text-rotate": ["coalesce", ["to-number", ["get", "bearing"]], 0],
          "text-rotation-alignment": "map",
          "text-allow-overlap": true,
          "text-ignore-placement": true,
        },
        paint: {
          "text-color": "#0284c7",
          "text-opacity": 0.92,
          "text-halo-color": "#e0f2fe",
          "text-halo-width": 1.1,
        },
      },
      {
        id: "traffic-active-direction-cones",
        type: "fill-extrusion",
        source: "trafficSignalActiveDirections",
        minzoom: 10,
        paint: {
          "fill-extrusion-color": "#22c55e",
          "fill-extrusion-height": [
            "interpolate",
            ["linear"],
            ["zoom"],
            10,
            4,
            14,
            13,
          ],
          "fill-extrusion-base": 0,
          "fill-extrusion-opacity": 0.96,
        },
      },
      {
        id: "traffic-active-direction-arrows",
        type: "symbol",
        source: "trafficSignalActiveDirections",
        minzoom: 10,
        layout: {
          "text-field": "▲",
          "text-font": ["Noto Sans Regular"],
          "text-size": [
            "interpolate",
            ["linear"],
            ["zoom"],
            10,
            10,
            13,
            14,
            16,
            18,
          ],
          "text-rotate": ["coalesce", ["to-number", ["get", "bearing"]], 0],
          "text-rotation-alignment": "map",
          "text-allow-overlap": true,
          "text-ignore-placement": true,
        },
        paint: {
          "text-color": "#16a34a",
          "text-opacity": 1,
          "text-halo-color": "#f0fdf4",
          "text-halo-width": 1.4,
        },
      },
      {
        id: "traffic-active-signal-points",
        type: "circle",
        source: "trafficSignalActivePoints",
        paint: {
          "circle-radius": [
            "interpolate",
            ["linear"],
            ["zoom"],
            11,
            4.4,
            16,
            7.4,
          ],
          "circle-color": "#22c55e",
          "circle-stroke-color": "#ffffff",
          "circle-stroke-width": 1.6,
          "circle-opacity": 0.96,
        },
      },
      {
        id: "hotspot-fill",
        type: "fill",
        source: "hotspots",
        paint: {
          "fill-color": [
            "match",
            ["get", "kind"],
            "automatic",
            "#ef4444",
            "#f59e0b",
          ],
          "fill-opacity": [
            "match",
            ["get", "kind"],
            "automatic",
            0.2,
            0.22,
          ],
        },
      },
      {
        id: "hotspot-outline",
        type: "line",
        source: "hotspots",
        layout: {
          "line-join": "round",
          "line-cap": "round",
        },
        paint: {
          "line-color": [
            "match",
            ["get", "kind"],
            "automatic",
            "#b91c1c",
            "#d97706",
          ],
          "line-width": [
            "interpolate",
            ["linear"],
            ["zoom"],
            10,
            2.1,
            15,
            4.2,
          ],
          "line-opacity": 0.95,
          "line-dasharray": [
            "match",
            ["get", "kind"],
            "automatic",
            ["literal", [0.7, 0.45]],
            ["literal", [1.2, 0.8]],
          ],
        },
      },
      {
        id: "hotspot-centers",
        type: "circle",
        source: "hotspotCenters",
        paint: {
          "circle-radius": [
            "interpolate",
            ["linear"],
            ["zoom"],
            10,
            4.5,
            15,
            7.5,
          ],
          "circle-color": [
            "match",
            ["get", "kind"],
            "automatic",
            "#ef4444",
            "#f59e0b",
          ],
          "circle-stroke-color": "#0f172a",
          "circle-stroke-width": 1.5,
        },
      },
      {
        id: "hotspot-labels",
        type: "symbol",
        source: "hotspotCenters",
        filter: ["!=", ["get", "label"], ""],
        layout: {
          "text-field": ["get", "label"],
          "text-size": [
            "interpolate",
            ["linear"],
            ["zoom"],
            10,
            10,
            16,
            13,
          ],
          "text-font": ["Noto Sans Bold"],
          "text-offset": [0, -2],
          "text-allow-overlap": true,
        },
        paint: {
          "text-color": [
            "match",
            ["get", "kind"],
            "automatic",
            "#7f1d1d",
            "#9a3412",
          ],
          "text-halo-color": "#ffffff",
          "text-halo-width": 1.4,
        },
      },
      {
        id: "vehicle-probe-fill",
        type: "fill",
        source: "vehicleProbeArea",
        paint: {
          "fill-color": "#22c55e",
          "fill-opacity": 0.12,
        },
      },
      {
        id: "vehicle-probe-outline",
        type: "line",
        source: "vehicleProbeArea",
        layout: {
          "line-join": "round",
          "line-cap": "round",
        },
        paint: {
          "line-color": "#15803d",
          "line-width": [
            "interpolate",
            ["linear"],
            ["zoom"],
            10,
            1.5,
            15,
            3.2,
          ],
          "line-opacity": 0.96,
          "line-dasharray": [1.1, 0.8],
        },
      },
      {
        id: "vehicle-probe-center",
        type: "circle",
        source: "vehicleProbeCenter",
        paint: {
          "circle-radius": [
            "interpolate",
            ["linear"],
            ["zoom"],
            10,
            5,
            16,
            8,
          ],
          "circle-color": "#16a34a",
          "circle-stroke-color": "#ffffff",
          "circle-stroke-width": 1.6,
        },
      },
      {
        id: "vehicle-probe-label",
        type: "symbol",
        source: "vehicleProbeCenter",
        layout: {
          "text-field": ["get", "label"],
          "text-size": [
            "interpolate",
            ["linear"],
            ["zoom"],
            10,
            11,
            16,
            14,
          ],
          "text-font": ["Noto Sans Bold"],
          "text-offset": [0, -2],
          "text-allow-overlap": true,
        },
        paint: {
          "text-color": "#14532d",
          "text-halo-color": "#ffffff",
          "text-halo-width": 1.4,
        },
      },
      {
        id: "synthverse-scan-fill",
        type: "fill",
        source: "synthverseScanArea",
        paint: {
          "fill-color": "#2563eb",
          "fill-opacity": 0.05,
        },
      },
      {
        id: "synthverse-scan-outline",
        type: "line",
        source: "synthverseScanArea",
        layout: {
          "line-join": "round",
          "line-cap": "round",
        },
        paint: {
          "line-color": "#1d4ed8",
          "line-width": [
            "interpolate",
            ["linear"],
            ["zoom"],
            9,
            1.1,
            15,
            2.4,
          ],
          "line-opacity": 0.55,
          "line-dasharray": [1.2, 0.9],
        },
      },
      {
        id: "traffic-event-zones-fill",
        type: "fill",
        source: "trafficEventZones",
        minzoom: 9,
        paint: {
          "fill-color": [
            "interpolate",
            ["linear"],
            ["coalesce", ["to-number", ["get", "trafficScore"]], 0],
            0,
            "rgba(96,165,250,0.16)",
            35,
            "rgba(245,158,11,0.22)",
            75,
            "rgba(239,68,68,0.28)",
          ],
          "fill-opacity": 1,
        },
      },
      {
        id: "traffic-event-zones-outline",
        type: "line",
        source: "trafficEventZones",
        minzoom: 9,
        layout: {
          "line-join": "round",
          "line-cap": "round",
        },
        paint: {
          "line-color": [
            "interpolate",
            ["linear"],
            ["coalesce", ["to-number", ["get", "trafficScore"]], 0],
            0,
            "#60a5fa",
            35,
            "#f59e0b",
            75,
            "#ef4444",
          ],
          "line-width": [
            "interpolate",
            ["linear"],
            ["zoom"],
            9,
            1.4,
            14,
            2.6,
          ],
          "line-opacity": 0.98,
        },
      },
      {
        id: "civic-points",
        type: "symbol",
        source: "civic",
        layout: {
          "icon-image": [
            "match",
            ["get", "assetType"],
            "hospital",
            MAP_ICON_IDS.hospital,
            "fire",
            MAP_ICON_IDS.fireStation,
            "police",
            MAP_ICON_IDS.policeStation,
            MAP_ICON_IDS.hospital,
          ],
          "icon-size": [
            "interpolate",
            ["linear"],
            ["zoom"],
            11,
            [
              "match",
              ["get", "assetType"],
              "hospital",
              0.34,
              "police",
              0.34,
              "fire",
              0.045,
              0.12,
            ],
            15,
            [
              "match",
              ["get", "assetType"],
              "hospital",
              0.46,
              "police",
              0.46,
              "fire",
              0.065,
              0.16,
            ],
          ],
          "icon-anchor": "center",
          "icon-allow-overlap": true,
          "icon-ignore-placement": true,
        },
        paint: {
          "icon-opacity": 0.95,
        },
      },
      {
        id: "synthverse-emergency-points",
        type: "circle",
        source: "synthverseEmergencyFacilities",
        paint: {
          "circle-radius": [
            "interpolate",
            ["linear"],
            ["zoom"],
            10,
            5.2,
            16,
            8.4,
          ],
          "circle-color": [
            "match",
            ["get", "assetType"],
            "hospital",
            "#14b8a6",
            "fire_station",
            "#f97316",
            "police_station",
            "#2563eb",
            "#64748b",
          ],
          "circle-stroke-color": "#ffffff",
          "circle-stroke-width": 1.5,
          "circle-opacity": 0.7,
        },
      },
      {
        id: "traffic-event-points",
        type: "circle",
        source: "trafficEvents",
        minzoom: 10,
        paint: {
          "circle-radius": [
            "interpolate",
            ["linear"],
            ["zoom"],
            10,
            [
              "interpolate",
              ["linear"],
              ["coalesce", ["to-number", ["get", "trafficScore"]], 0],
              0,
              4,
              90,
              8,
            ],
            16,
            [
              "interpolate",
              ["linear"],
              ["coalesce", ["to-number", ["get", "trafficScore"]], 0],
              0,
              6,
              90,
              11,
            ],
          ],
          "circle-color": [
            "interpolate",
            ["linear"],
            ["coalesce", ["to-number", ["get", "trafficScore"]], 0],
            0,
            "#60a5fa",
            35,
            "#f59e0b",
            75,
            "#ef4444",
          ],
          "circle-stroke-color": "#ffffff",
          "circle-stroke-width": 1.5,
          "circle-opacity": 0.98,
        },
      },
      {
        id: "traffic-signal-points",
        type: "circle",
        source: "trafficSignals",
        paint: {
          "circle-radius": [
            "interpolate",
            ["linear"],
            ["zoom"],
            11,
            3.2,
            16,
            5.2,
          ],
          "circle-color": "#ef4444",
          "circle-stroke-color": "#ffffff",
          "circle-stroke-width": 1.2,
          "circle-opacity": 0.7,
        },
      },
      {
        id: "traffic-heatmap",
        type: "heatmap",
        source: "trafficHeatmap",
        maxzoom: 16,
        paint: {
          "heatmap-weight": ["coalesce", ["to-number", ["get", "weight"]], 0],
          "heatmap-intensity": [
            "interpolate",
            ["linear"],
            ["zoom"],
            9,
            1,
            13,
            1.25,
            16,
            1.55,
          ],
          "heatmap-color": [
            "interpolate",
            ["linear"],
            ["heatmap-density"],
            0,
            "rgba(37,99,235,0)",
            0.08,
            "rgba(147,197,253,0.48)",
            0.22,
            "rgba(59,130,246,0.66)",
            0.4,
            "rgba(6,182,212,0.76)",
            0.68,
            "rgba(245,158,11,0.84)",
            1,
            "rgba(239,68,68,0.96)",
          ],
          "heatmap-radius": [
            "interpolate",
            ["linear"],
            ["zoom"],
            9,
            24,
            12,
            34,
            16,
            52,
          ],
          "heatmap-opacity": [
            "interpolate",
            ["linear"],
            ["zoom"],
            9,
            0.84,
            14,
            0.76,
            16,
            0.62,
          ],
        },
      },
      {
        id: "water-zones-fill",
        type: "fill",
        source: "waterZones",
        paint: {
          "fill-color": ["coalesce", ["get", "metricColor"], "#bae6fd"],
          "fill-opacity": 0.07,
        },
      },
      {
        id: "water-zones-outline",
        type: "line",
        source: "waterZones",
        layout: {
          "line-join": "round",
          "line-cap": "round",
        },
        paint: {
          "line-color": ["coalesce", ["get", "metricColor"], "#0284c7"],
          "line-width": [
            "interpolate",
            ["linear"],
            ["zoom"],
            10,
            0.9,
            15,
            1.8,
          ],
          "line-opacity": 0.42,
        },
      },
      {
        id: "water-grid-casing",
        type: "line",
        source: "waterGridVisible",
        minzoom: 10.6,
        layout: {
          "line-cap": "round",
          "line-join": "round",
        },
        paint: {
          "line-color": "#0f172a",
          "line-width": ["+", ["coalesce", ["get", "lineWidth"], 1.3], 1.4],
          "line-opacity": 0.18,
        },
      },
      {
        id: "water-grid-context",
        type: "line",
        source: "waterGridVisible",
        minzoom: 10.6,
        layout: {
          "line-cap": "round",
          "line-join": "round",
        },
        paint: {
          "line-color": "#e2e8f0",
          "line-width": ["+", ["coalesce", ["get", "lineWidth"], 1.1], 0.45],
          "line-opacity": ["coalesce", ["get", "contextOpacity"], 0.2],
        },
      },
      {
        id: "water-grid-flow",
        type: "line",
        source: "waterGridVisible",
        minzoom: 10.6,
        layout: {
          "line-cap": "round",
          "line-join": "round",
        },
        paint: {
          "line-color": ["coalesce", ["get", "lineColor"], "#0284c7"],
          "line-width": ["coalesce", ["get", "lineWidth"], 1.1],
          "line-opacity": ["coalesce", ["get", "lineOpacity"], 0.78],
        },
      },
      {
        id: "water-grid-affected",
        type: "line",
        source: "waterGridVisible",
        minzoom: 10.6,
        filter: ["==", ["coalesce", ["get", "isAffected"], 0], 1],
        layout: {
          "line-cap": "round",
          "line-join": "round",
        },
        paint: {
          "line-color": "#f97316",
          "line-width": ["+", ["coalesce", ["get", "lineWidth"], 1.1], 0.8],
          "line-opacity": 0.62,
        },
      },
      {
        id: "water-grid-broken",
        type: "line",
        source: "waterGridVisible",
        minzoom: 10.6,
        filter: ["==", ["coalesce", ["get", "isBroken"], 0], 1],
        layout: {
          "line-cap": "round",
          "line-join": "round",
        },
        paint: {
          "line-color": "#dc2626",
          "line-width": ["+", ["coalesce", ["get", "lineWidth"], 1.2], 1.6],
          "line-opacity": 0.98,
          "line-dasharray": [1.2, 0.8],
        },
      },
      {
        id: "water-break-halo",
        type: "circle",
        source: "waterBreaks",
        paint: {
          "circle-radius": [
            "interpolate",
            ["linear"],
            ["zoom"],
            11,
            12,
            16,
            22,
          ],
          "circle-color": [
            "match",
            ["get", "incidentType"],
            "reservoirFailure",
            "#2563eb",
            "#dc2626",
          ],
          "circle-opacity": 0.12,
        },
      },
      {
        id: "water-break-point",
        type: "circle",
        source: "waterBreaks",
        paint: {
          "circle-radius": [
            "interpolate",
            ["linear"],
            ["zoom"],
            11,
            5,
            16,
            9,
          ],
          "circle-color": [
            "match",
            ["get", "incidentType"],
            "reservoirFailure",
            "#2563eb",
            "#dc2626",
          ],
          "circle-stroke-color": "#ffffff",
          "circle-stroke-width": 1.4,
          "circle-opacity": 0.7,
        },
      },
      {
        id: "water-valves",
        type: "circle",
        source: "waterValves",
        minzoom: 14.4,
        paint: {
          "circle-radius": [
            "interpolate",
            ["linear"],
            ["zoom"],
            14.4,
            1.5,
            17,
            3.4,
          ],
          "circle-color": "#f59e0b",
          "circle-stroke-color": "#ffffff",
          "circle-stroke-width": 0.8,
          "circle-opacity": 0.7,
        },
      },
      {
        id: "water-nodes",
        type: "circle",
        source: "waterNodes",
        filter: [
          "any",
          ["==", ["get", "nodeType"], "district"],
          ["==", ["get", "nodeType"], "pump"],
        ],
        paint: {
          "circle-radius": [
            "interpolate",
            ["linear"],
            ["zoom"],
            10,
            [
              "match",
              ["get", "nodeType"],
              "source",
              6.2,
              "pump",
              5.4,
              "tank",
              5.1,
              4.1,
            ],
            15,
            [
              "match",
              ["get", "nodeType"],
              "source",
              10.2,
              "pump",
              8.1,
              "tank",
              7.2,
              5.8,
            ],
          ],
          "circle-color": ["coalesce", ["get", "metricColor"], "#0284c7"],
          "circle-stroke-color": "#ffffff",
          "circle-stroke-width": 1.3,
          "circle-opacity": [
            "match",
            ["get", "nodeType"],
            "district",
            0.7,
            0.7,
          ],
        },
      },
      {
        id: "water-reservoir-icons",
        type: "symbol",
        source: "waterNodes",
        minzoom: 10.8,
        filter: [
          "any",
          ["==", ["get", "nodeType"], "source"],
          ["==", ["get", "nodeType"], "tank"],
        ],
        layout: {
          "icon-image": MAP_ICON_IDS.waterReservoir,
          "icon-size": [
            "interpolate",
            ["linear"],
            ["zoom"],
            10.8,
            0.42,
            16,
            0.66,
          ],
          "icon-allow-overlap": true,
        },
      },
      {
        id: "power-zones-fill",
        type: "fill",
        source: "powerZones",
        paint: {
          "fill-color": ["coalesce", ["get", "metricColor"], "#fde68a"],
          "fill-opacity": 0.06,
        },
      },
      {
        id: "power-zones-outline",
        type: "line",
        source: "powerZones",
        layout: {
          "line-join": "round",
          "line-cap": "round",
        },
        paint: {
          "line-color": ["coalesce", ["get", "metricColor"], "#d97706"],
          "line-width": [
            "interpolate",
            ["linear"],
            ["zoom"],
            10,
            0.9,
            15,
            1.8,
          ],
          "line-opacity": 0.4,
        },
      },
      {
        id: "power-grid-casing",
        type: "line",
        source: "powerGridVisible",
        minzoom: 10.8,
        layout: {
          "line-cap": "round",
          "line-join": "round",
        },
        paint: {
          "line-color": "#111827",
          "line-width": ["+", ["coalesce", ["get", "lineWidth"], 1.1], 1.2],
          "line-opacity": 0.14,
        },
      },
      {
        id: "power-grid-flow",
        type: "line",
        source: "powerGridVisible",
        minzoom: 10.8,
        layout: {
          "line-cap": "round",
          "line-join": "round",
        },
        paint: {
          "line-color": ["coalesce", ["get", "lineColor"], "#f59e0b"],
          "line-width": ["coalesce", ["get", "lineWidth"], 1.1],
          "line-opacity": ["coalesce", ["get", "lineOpacity"], 0.72],
        },
      },
      {
        id: "power-grid-affected",
        type: "line",
        source: "powerGridVisible",
        minzoom: 10.8,
        filter: ["==", ["coalesce", ["get", "isIncidentAffected"], 0], 1],
        layout: {
          "line-cap": "round",
          "line-join": "round",
        },
        paint: {
          "line-color": "#f97316",
          "line-width": ["+", ["coalesce", ["get", "lineWidth"], 1.1], 0.8],
          "line-opacity": 0.58,
        },
      },
      {
        id: "power-grid-faulted",
        type: "line",
        source: "powerGridVisible",
        minzoom: 10.8,
        filter: ["==", ["coalesce", ["get", "isFaulted"], 0], 1],
        layout: {
          "line-cap": "round",
          "line-join": "round",
        },
        paint: {
          "line-color": "#dc2626",
          "line-width": ["+", ["coalesce", ["get", "lineWidth"], 1.1], 1.4],
          "line-opacity": 0.96,
          "line-dasharray": [1, 0.7],
        },
      },
      {
        id: "power-substations",
        type: "symbol",
        source: "powerNodes",
        minzoom: 11.3,
        filter: ["==", ["get", "nodeType"], "substation"],
        layout: {
          "icon-image": MAP_ICON_IDS.powerSubstation,
          "icon-size": [
            "interpolate",
            ["linear"],
            ["zoom"],
            11.3,
            0.42,
            16,
            0.68,
          ],
          "icon-allow-overlap": true,
        },
      },
      {
        id: "power-transformers",
        type: "circle",
        source: "powerTransformers",
        minzoom: 13.8,
        paint: {
          "circle-radius": [
            "interpolate",
            ["linear"],
            ["zoom"],
            13.8,
            1.2,
            17,
            3,
          ],
          "circle-color": "#14b8a6",
          "circle-stroke-color": "#ffffff",
          "circle-stroke-width": 0.7,
          "circle-opacity": 0.7,
        },
      },
      {
        id: "power-nodes",
        type: "circle",
        source: "powerNodes",
        filter: [
          "any",
          ["==", ["get", "nodeType"], "district"],
          ["==", ["get", "nodeType"], "source"],
        ],
        paint: {
          "circle-radius": [
            "interpolate",
            ["linear"],
            ["zoom"],
            10,
            [
              "match",
              ["get", "nodeType"],
              "source",
              6.2,
              "substation",
              5.2,
              4.2,
            ],
            15,
            [
              "match",
              ["get", "nodeType"],
              "source",
              9.8,
              "substation",
              7.4,
              5.8,
            ],
          ],
          "circle-color": ["coalesce", ["get", "metricColor"], "#f59e0b"],
          "circle-stroke-color": "#ffffff",
          "circle-stroke-width": 1.2,
          "circle-opacity": [
            "match",
            ["get", "nodeType"],
            "district",
            0.7,
            0.7,
          ],
        },
      },
      {
        id: "power-incident-halo",
        type: "circle",
        source: "powerIncidents",
        paint: {
          "circle-radius": [
            "interpolate",
            ["linear"],
            ["zoom"],
            11,
            10,
            16,
            18,
          ],
          "circle-color": [
            "match",
            ["get", "incidentType"],
            "substationOutage",
            "#f59e0b",
            "#dc2626",
          ],
          "circle-opacity": 0.13,
        },
      },
      {
        id: "power-incident-point",
        type: "circle",
        source: "powerIncidents",
        paint: {
          "circle-radius": [
            "interpolate",
            ["linear"],
            ["zoom"],
            11,
            4.5,
            16,
            8,
          ],
          "circle-color": [
            "match",
            ["get", "incidentType"],
            "substationOutage",
            "#f59e0b",
            "#dc2626",
          ],
          "circle-stroke-color": "#ffffff",
          "circle-stroke-width": 1.2,
          "circle-opacity": 0.7,
        },
      },
      {
        id: "route-casing",
        type: "line",
        source: "route",
        layout: {
          "line-cap": "round",
          "line-join": "round",
        },
        paint: {
          "line-color": "#082032",
          "line-width": [
            "interpolate",
            ["linear"],
            ["zoom"],
            10,
            6,
            16,
            10,
          ],
        },
      },
      {
        id: "route-line",
        type: "line",
        source: "route",
        layout: {
          "line-cap": "round",
          "line-join": "round",
        },
        paint: {
          "line-color": "#22c55e",
          "line-width": [
            "interpolate",
            ["linear"],
            ["zoom"],
            10,
            3,
            16,
            5.5,
          ],
        },
      },
      {
        id: "route-endpoints",
        type: "circle",
        source: "routeEndpoints",
        paint: {
          "circle-radius": [
            "interpolate",
            ["linear"],
            ["zoom"],
            10,
            6,
            16,
            9,
          ],
          "circle-color": [
            "match",
            ["get", "role"],
            "start",
            "#22c55e",
            "end",
            "#38bdf8",
            "#ffffff",
          ],
          "circle-stroke-color": "#ffffff",
          "circle-stroke-width": 2,
          "circle-opacity": 0.7,
        },
      },
      {
        id: "vehicle-points",
        type: "circle",
        source: "vehicles",
        paint: {
          "circle-radius": [
            "interpolate",
            ["linear"],
            ["zoom"],
            10,
            4.2,
            16,
            7.4,
          ],
          "circle-color": ["coalesce", ["get", "color"], "#0f172a"],
          "circle-stroke-color": "#ffffff",
          "circle-stroke-width": 1.4,
          "circle-opacity": 0.7,
        },
      },
      {
        id: "civic-labels",
        type: "symbol",
        source: "civic",
        minzoom: 12,
        filter: ["!=", ["get", "label"], ""],
        layout: {
          "text-field": ["get", "label"],
          "text-size": [
            "interpolate",
            ["linear"],
            ["zoom"],
            12,
            10,
            16,
            13,
          ],
          "text-offset": [0.9, 0],
          "text-anchor": "left",
        },
        paint: {
          "text-color": "#17212b",
          "text-halo-color": "#ffffff",
          "text-halo-width": 1.3,
        },
      },
      {
        id: "traffic-event-labels",
        type: "symbol",
        source: "trafficEvents",
        minzoom: 12,
        filter: ["!=", ["get", "label"], ""],
        layout: {
          "text-field": ["get", "label"],
          "text-size": [
            "interpolate",
            ["linear"],
            ["zoom"],
            12,
            10,
            16,
            13,
          ],
          "text-offset": [0.9, 0],
          "text-anchor": "left",
        },
        paint: {
          "text-color": "#7c2d12",
          "text-halo-color": "#ffffff",
          "text-halo-width": 1.3,
        },
      },
      {
        id: "synthverse-emergency-labels",
        type: "symbol",
        source: "synthverseEmergencyFacilities",
        minzoom: 12,
        filter: ["!=", ["get", "label"], ""],
        layout: {
          "text-field": ["get", "label"],
          "text-size": [
            "interpolate",
            ["linear"],
            ["zoom"],
            12,
            10,
            16,
            13,
          ],
          "text-offset": [0.9, 0],
          "text-anchor": "left",
        },
        paint: {
          "text-color": "#17212b",
          "text-halo-color": "#ffffff",
          "text-halo-width": 1.3,
        },
      },
      {
        id: "water-node-labels",
        type: "symbol",
        source: "waterNodes",
        minzoom: 11,
        filter: ["==", ["get", "showLabel"], true],
        layout: {
          "text-field": ["get", "label"],
          "text-size": [
            "interpolate",
            ["linear"],
            ["zoom"],
            11,
            10,
            16,
            13,
          ],
          "text-offset": [0, 1.1],
          "text-anchor": "top",
        },
        paint: {
          "text-color": "#082f49",
          "text-halo-color": "#ffffff",
          "text-halo-width": 1.2,
        },
      },
      {
        id: "traffic-signal-labels",
        type: "symbol",
        source: "trafficSignals",
        minzoom: 12,
        filter: ["!=", ["get", "label"], ""],
        layout: {
          "text-field": ["get", "label"],
          "text-size": 11,
          "text-offset": [0.9, 0],
          "text-anchor": "left",
        },
        paint: {
          "text-color": "#4b0f0f",
          "text-halo-color": "#ffffff",
          "text-halo-width": 1.3,
        },
      },
      ...labelLayers,
    ],
  };
}

export function updateGeoJsonSource(mapInstance, sourceId, data) {
  const source = mapInstance.getSource(sourceId);

  if (source) {
    source.setData(data);
  }
}

export async function ensureMapImages(mapInstance) {
  await Promise.all([
    ensureSingleMapImage(
      mapInstance,
      MAP_ICON_IDS.waterReservoir,
      new URL(MAP_ICON_PATHS.waterReservoir, window.location.origin).toString(),
    ),
    ensureSingleMapImage(
      mapInstance,
      MAP_ICON_IDS.powerSubstation,
      new URL(MAP_ICON_PATHS.powerSubstation, window.location.origin).toString(),
    ),
    ensureSingleMapImage(
      mapInstance,
      MAP_ICON_IDS.hospital,
      new URL(MAP_ICON_PATHS.hospital, window.location.origin).toString(),
    ),
    ensureSingleMapImage(
      mapInstance,
      MAP_ICON_IDS.fireStation,
      new URL(MAP_ICON_PATHS.fireStation, window.location.origin).toString(),
    ),
    ensureSingleMapImage(
      mapInstance,
      MAP_ICON_IDS.policeStation,
      new URL(MAP_ICON_PATHS.policeStation, window.location.origin).toString(),
    ),
  ]);
}

async function ensureSingleMapImage(mapInstance, imageId, imageUrl) {
  if (mapInstance.hasImage(imageId)) {
    return;
  }

  const response = await fetch(imageUrl);

  if (!response.ok) {
    throw new Error(`Failed to load map image: ${imageUrl}`);
  }

  const imageBlob = await response.blob();
  const imageBitmap = await createImageBitmap(imageBlob);

  if (!mapInstance.hasImage(imageId)) {
    mapInstance.addImage(imageId, imageBitmap);
  }
}

export function attachCursor(mapInstance, layerId, pickModeRef) {
  mapInstance.on("mouseenter", layerId, () => {
    mapInstance.getCanvas().style.cursor = pickModeRef.current ? "crosshair" : "pointer";
  });

  mapInstance.on("mouseleave", layerId, () => {
    mapInstance.getCanvas().style.cursor = pickModeRef.current ? "crosshair" : "";
  });
}
